# Generated by Django 5.0.2 on 2024-04-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0002_alter_document_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
